using System;
using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("1.0.0")]
[assembly: AssemblyTitleAttribute("JIRAConnector.Communication.dll")]
[assembly: AssemblyDescriptionAttribute("")]
[assembly: AssemblyInformationalVersionAttribute("Beta 1")]

