//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JIRAConnector.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JIRAConnector.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap jira_connector_logo {
            get {
                object obj = ResourceManager.GetObject("jira_connector_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JiraConnector_Img_bug {
            get {
                object obj = ResourceManager.GetObject("JiraConnector_Img_bug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JiraConnector_Img_Calendar {
            get {
                object obj = ResourceManager.GetObject("JiraConnector_Img_Calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JiraConnector_Img_improvement {
            get {
                object obj = ResourceManager.GetObject("JiraConnector_Img_improvement", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JiraConnector_Img_Info1 {
            get {
                object obj = ResourceManager.GetObject("JiraConnector_Img_Info1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JiraConnector_Img_Info2 {
            get {
                object obj = ResourceManager.GetObject("JiraConnector_Img_Info2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JiraConnector_Img_logo {
            get {
                object obj = ResourceManager.GetObject("JiraConnector_Img_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JiraConnector_Img_newfeature {
            get {
                object obj = ResourceManager.GetObject("JiraConnector_Img_newfeature", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JiraConnector_Img_Pencil1 {
            get {
                object obj = ResourceManager.GetObject("JiraConnector_Img_Pencil1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JiraConnector_Img_Pencil2 {
            get {
                object obj = ResourceManager.GetObject("JiraConnector_Img_Pencil2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JiraConnector_Img_priority_blocker {
            get {
                object obj = ResourceManager.GetObject("JiraConnector_Img_priority_blocker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JiraConnector_Img_priority_critical {
            get {
                object obj = ResourceManager.GetObject("JiraConnector_Img_priority_critical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JiraConnector_Img_priority_major {
            get {
                object obj = ResourceManager.GetObject("JiraConnector_Img_priority_major", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JiraConnector_Img_priority_minor {
            get {
                object obj = ResourceManager.GetObject("JiraConnector_Img_priority_minor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JiraConnector_Img_priority_trivial {
            get {
                object obj = ResourceManager.GetObject("JiraConnector_Img_priority_trivial", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JiraConnector_Img_refresh {
            get {
                object obj = ResourceManager.GetObject("JiraConnector_Img_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JiraConnector_Img_RefreshIssues {
            get {
                object obj = ResourceManager.GetObject("JiraConnector_Img_RefreshIssues", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JiraConnector_Img_RefreshIssues1 {
            get {
                object obj = ResourceManager.GetObject("JiraConnector_Img_RefreshIssues1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JiraConnector_Img_Start_Icon {
            get {
                object obj = ResourceManager.GetObject("JiraConnector_Img_Start_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JiraConnector_Img_status_closed {
            get {
                object obj = ResourceManager.GetObject("JiraConnector_Img_status_closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JiraConnector_Img_status_open {
            get {
                object obj = ResourceManager.GetObject("JiraConnector_Img_status_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JiraConnector_Img_status_reopened {
            get {
                object obj = ResourceManager.GetObject("JiraConnector_Img_status_reopened", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JiraConnector_Img_status_resolved {
            get {
                object obj = ResourceManager.GetObject("JiraConnector_Img_status_resolved", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JiraConnector_Img_status_unassigned {
            get {
                object obj = ResourceManager.GetObject("JiraConnector_Img_status_unassigned", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JiraConnector_Img_StatusInProgress {
            get {
                object obj = ResourceManager.GetObject("JiraConnector_Img_StatusInProgress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JiraConnector_Img_StatusResolved {
            get {
                object obj = ResourceManager.GetObject("JiraConnector_Img_StatusResolved", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JiraConnector_Img_Stop_Icon {
            get {
                object obj = ResourceManager.GetObject("JiraConnector_Img_Stop_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JiraConnector_Img_task {
            get {
                object obj = ResourceManager.GetObject("JiraConnector_Img_task", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh_icon2 {
            get {
                object obj = ResourceManager.GetObject("refresh_icon2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
